### ISSUE TITLE
大佬 有关mistGPU报错的一个问题

### ISSUE THREAD

**Issue by shinenine** [Gnomeek/ChineseSentimentAnalysiswithBERT#3]
想请教一下我每次使用mistGPU想训练时，都会报No module named ‘fused_layer_norm_cuda’的错误。
网上查了很多 都说是apex包的问题，但是我按照教程操作后也还是报这个错，请问下要怎么解决呀。

**Comment by Gnomeek** [comment]
去mist gpu提ticket？看起来是pytorch和cuda的问题。
